### ISSUE TITLE
Troublesome index settings[BUG]

### ISSUE THREAD

**Issue by pandu-k** [marqo-ai/marqo#392] opened 2023-03-15 22:54 UTC
**Describe the bug**
A 5xx was caused by creating an index with these settings

**To Reproduce**
Create an index with these settings:

```
index_settings = {
                    "index_defaults": {
                        "treat_urls_and_pointers_as_images": True,
                        "model": 'open_clip/coca_ViT-L-14/laion2b_s13b_b90k',
                        "normalize_embeddings": True,
                        "text_preprocessing": {
                            "split_length": 10,
                            "split_overlap": 2,
                            "split_method": "sentence"
                        },
                    },         
                'number_of_shards':60,
        }
```

**Comment by wanliAlex** [comment] 2023-03-17 01:41
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/49334982/225790367-cb423b9e-13d7-4b9b-915c-a9714144b41a.png">
this error can be reproduced on `mainline` using the provided `index_settings`

**Comment by wanliAlex** [comment] 2023-03-17 03:14
I can't reproduce the error on the mainline. maybe it's fixed in PR (https://github.com/marqo-ai/marqo/pull/387)

**Closed as completed** 2023-03-20 05:57 UTC
Labels: bug
